### PR TITLE
feat: navigation (resolves #14)

### LINKED ISSUE #14: Component: navigation
Implement navigation bar with all states.

## Additional context or notes

https://www.figma.com/file/LXnq7rdbsr2yyxOG2rSh5S/Inclusive-Design-Guide-2023?type=design&node-id=17-965&mode=design&t=WibM2Mq2lHqyiZx8-4

### PR DESCRIPTION
**Pull request by greatislander**
- [x] Mobile navigation
- [x] Desktop navigation

### CODE REVIEW

**Review by chosww — CHANGES_REQUESTED** [review]
Thanks @greatislander, I found some mismatches between the preview site and the Figma design. Also, @cherylhjli, should current tab style go away when another menu item is in either focus, hover, or active state?

**Comment by chosww** [comment]
@cherylhjli: in regards to the question I asked -- this is when current tab is Practices and focus is on Activities.

Screen Shot 2023-07-25 at 1 10 14 PM

**Comment by cherylhjli** [comment]
@chosww yes, it should show current page when hovering or focusing on another link. I'll update the focus state so it looks less funny.

**Comment by greatislander** [comment]
@chosww I believe all the review comments are addressed now.

**Review by chosww — APPROVED** [review]

**Pull request merged**
